#!/usr/bin/env node
/**
 * Reads pkg/djvu_rs_bg.wasm and writes src/wasm_inline.ts containing the
 * WASM bytes as a base64 string constant.
 *
 * Run via: npm run embed:wasm
 * Called automatically by npm run build / npm run dev.
 */

import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const pkgDir = join(root, 'pkg');
const wasmPath = join(pkgDir, 'djvu_rs_bg.wasm');

// ── Preflight ─────────────────────────────────────────────────────────────────

if (!existsSync(pkgDir)) {
  console.error(
    '\n[embed-wasm] ERROR: pkg/ directory not found.\n' +
    '  The WASM package must be built before bundling the plugin.\n\n' +
    '  Run:\n' +
    '    npm run build:wasm\n'
  );
  process.exit(1);
}

if (!existsSync(wasmPath)) {
  console.error(
    '\n[embed-wasm] ERROR: pkg/djvu_rs_bg.wasm not found.\n' +
    '  pkg/ exists but the WASM binary is missing — re-run the WASM build.\n\n' +
    '  Run:\n' +
    '    npm run build:wasm\n'
  );
  process.exit(1);
}

// ── Embed ─────────────────────────────────────────────────────────────────────

const wasm = readFileSync(wasmPath);
const b64 = wasm.toString('base64');
const out = join(root, 'src', 'wasm_inline.ts');

writeFileSync(
  out,
  `// Auto-generated by scripts/embed-wasm.mjs — do not edit or commit.\n` +
  `// Re-run: npm run embed:wasm\n` +
  `export const WASM_BASE64 =\n  "${b64}";\n`
);

console.log(
  `[embed-wasm] ${wasm.length.toLocaleString()} bytes → base64 ` +
  `(${b64.length.toLocaleString()} chars) → src/wasm_inline.ts`
);
