#!/usr/bin/env node
/**
 * Reads pkg/djvu_rs_bg.wasm and writes src/wasm_inline.ts containing the
 * WASM bytes as a base64 string constant.
 *
 * Run via: npm run embed:wasm
 * Called automatically by npm run build / npm run dev.
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const wasmPath = join(root, 'pkg', 'djvu_rs_bg.wasm');

let wasm;
try {
  wasm = readFileSync(wasmPath);
} catch {
  console.error(
    '\n[embed-wasm] ERROR: pkg/djvu_rs_bg.wasm not found.\n' +
    '  Run: npm run build:wasm\n'
  );
  process.exit(1);
}

const b64 = wasm.toString('base64');
const out = join(root, 'src', 'wasm_inline.ts');

writeFileSync(
  out,
  `// Auto-generated by scripts/embed-wasm.mjs — do not edit or commit.\n` +
  `// Re-run: npm run embed:wasm\n` +
  `export const WASM_BASE64 =\n  "${b64}";\n`
);

console.log(
  `[embed-wasm] ${wasm.length.toLocaleString()} bytes → base64 (${b64.length.toLocaleString()} chars) → src/wasm_inline.ts`
);
